version: '3'

services:

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
    volumes:
      - dbdata:/var/lib/mysql

  spider:
    build:
      context: .
      dockerfile: Spider.Dockerfile
    volumes:
      - ".:/app"
    entrypoint: scrapy crawl transfermark

volumes:
  dbdata: