version: '3'

services:

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 6s
      retries: 10

  spider:
    build:
      context: .
      dockerfile: Spider.Dockerfile
    volumes:
      - ".:/app"
    env_file:
      - dev.env
    entrypoint: scrapy crawl transfermark -a season=2022
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: App.Dockerfile
    ports:
      - '6000:5000'
    env_file:
      - dev.env
    volumes:
      - ".:/app"
    depends_on:
      db:
        condition: service_healthy

  ui:
    build:
      context: .
      dockerfile: UI.Dockerfile
    volumes:
      - "./qa-app:/app"
    ports:
      - '3000:80'
    depends_on:
      - app
      - db

  proxy:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ui
      - app

volumes:
  dbdata: